--- #YAML:1.0
name:               Dpchrist-Debug
version:            1.043
abstract:           debugging convenience routines
author:
    - David Paul Christensen <dpchrist@holgerdanske.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Capture::Tiny:        0
    Dpchrist::File::Append:  1.03
    Dpchrist::Module:     1.025
    Dpchrist::Tag:        1.034
    feature:              0
    File::Slurp:          0
    Getopt::Long:         0
    Pod::Html:            0
    Pod::Text:            0
    Pod::Usage:           0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.54
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
